### ISSUE TITLE
dataset problem 

### ISSUE THREAD

**Issue by wuhaoranran** [Lllllolita/CAN_Paddle#2]
how can i see the picture inside the CROHME dataset,take 14_test_images.pkl as an example

**Comment by Lllllolita** [comment]
You can try the following code to see the first picture in '14_test_images.pkl'.
```
import pickle as pkl
from PIL import Image
import matplotlib.pyplot as plt

with open("14_test_images.pkl", 'rb')as f:
    images = pkl.load(f)
image_names = list(images.keys())
img = Image.fromarray(images[image_names[0]]).convert("1")
plt.imshow(img)
plt.show()
```

**Comment by Lllllolita** [comment]
Excuse me, have you solved the problem?

**Comment by wuhaoranran** [comment]
> Excuse me, have you solved the problem?

yes,thanks so much ,and apologize for my late reply
